# Generated by Django 3.0.5 on 2020-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm20id', models.TextField()),
                ('wikidata_object', models.TextField()),
                ('name', models.TextField()),
                ('birthday', models.DateTimeField()),
                ('deathday', models.DateTimeField(null=True)),
                ('position_held', models.TextField()),
                ('position_held_startdate', models.DateTimeField()),
                ('position_held_enddate', models.DateTimeField()),
                ('picture', models.TextField(null=True)),
                ('country', models.TextField()),
            ],
        ),
    ]
