# Generated by Django 2.2.6 on 2020-05-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm20idLabdel', models.TextField()),
                ('person', models.TextField()),
                ('personLabel', models.TextField()),
                ('birthday', models.DateTimeField()),
                ('deathday', models.DateTimeField()),
                ('position_heldLabel', models.TextField()),
                ('startdate', models.DateTimeField()),
                ('picture', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
    ]
