# Generated by Django 2.2.8 on 2020-06-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='jahr',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='position_held_start_EU',
            field=models.TextField(default=0),
        ),
    ]
