# Generated by Django 3.0.5 on 2020-06-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='deathday',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='position_held_enddate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='position_held_startdate',
            field=models.TextField(),
        ),
    ]
