# Generated by Django 2.2.8 on 2020-06-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20200616_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position_held_end_EU',
            field=models.TextField(default=0),
        ),
    ]
