# Generated by Django 2.2.8 on 2020-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_person_position_held_end_eu'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthdayEU',
            field=models.TextField(default=0),
        ),
    ]
