# Generated by Django 2.2.8 on 2020-06-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20200607_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='wikidata_object',
            field=models.URLField(),
        ),
    ]
