# Generated by Django 3.0.5 on 2020-06-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20200608_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='predecessor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='religion',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='person',
            name='successor',
            field=models.TextField(null=True),
        ),
    ]
