# Generated by Django 2.2.8 on 2020-06-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_person_birthdayeu'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deathdayEU',
            field=models.TextField(default=0),
        ),
    ]
