# Generated by Django 2.2.8 on 2020-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_person_deathdayeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='jahr',
            field=models.TextField(default=0, null=True),
        ),
    ]
